#Change bind key from CTRL-B to CTRL-A
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g history-limit 19000
set -g mouse on
set -s escape-time 0
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Proper terminal colors
set -g default-terminal "tmux-256color"

# Vi mode and Clipboard
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
if-shell "uname | grep -q Darwin" \
  'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"' \
  'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -sel clip -i"'

# Maintain path when splitting
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "Config reloaded!"